name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.7
          - 3.9

    steps:
      - uses: dhvcc/python-poetry-setup@master
        with:
          python-version: ${{ matrix.python-version }}
          cache-key: ${{ matrix.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/poetry.lock') }}

      - name: Run flake8
        run: |
          poetry run flake8

      - name: Run mypy
        run: |
          poetry run mypy vkbottle

      - name: Run tests
        run: |
          poetry run pytest
